//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedAfricaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string COUNRTY { get; set; }
        public string REGISTARTIONNUMBER { get; set; }
        public string CONTACTPERSON { get; set; }
        public string CONTACTNUM { get; set; }
    }
}
