//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedAfricaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        public int ID { get; set; }
        public string SIZE { get; set; }
        public Nullable<int> TCLOTHES { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual TCLOTHE TCLOTHE { get; set; }
    }
}
