//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedAfricaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONOR()
        {
            this.DONATIONs = new HashSet<DONATION>();
        }
    
        public string DONOR_ID { get; set; }
        public string COMPANY { get; set; }
        public string COUNTRY { get; set; }
        public string PERSON_ID { get; set; }
        public Nullable<int> TITLE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONATION> DONATIONs { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual TITLE TITLE { get; set; }
    }
}
