//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedAfricaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVEN()
        {
            this.DONATIONs = new HashSet<DONATION>();
            this.EVENT_IMAGED = new HashSet<EVENT_IMAGED>();
            this.SPONSORSHIPs = new HashSet<SPONSORSHIP>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DATES { get; set; }
        public Nullable<int> AMOUNTRAISED { get; set; }
        public Nullable<int> TEVENS { get; set; }
        public string VIDEO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONATION> DONATIONs { get; set; }
        public virtual TEVEN TEVEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT_IMAGED> EVENT_IMAGED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPONSORSHIP> SPONSORSHIPs { get; set; }
    }
}
