//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedAfricaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOLUNTEER
    {
        public string VOLUNTEER_ID { get; set; }
        public Nullable<System.DateTime> START { get; set; }
        public Nullable<System.DateTime> ENDS { get; set; }
        public string PERSON_ID { get; set; }
        public Nullable<int> TITLE_ID { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual TITLE TITLE { get; set; }
    }
}
