USE MASTER
GO

ALTER DATABASE FEEDAFRICA SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE FEEDAFRICA

CREATE DATABASE FEEDAFRICA
GO
USE FEEDAFRICA
GO

CREATE TABLE PERSON
(
	PERSON_ID  VARCHAR(20) PRIMARY KEY,
	NAME VARCHAR(20),
	SURNAME VARCHAR (20),
	IDENTITY_NUMBER VARCHAR(13),
	EMAIL VARCHAR (50),	
	PHONE VARCHAR (10)
)

CREATE TABLE TITLE
(
	TITLE_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(20)
)
CREATE TABLE BRANCH 
(
	ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(20)
)

CREATE TABLE SYSTEMUSERTYPE
(
	SYSTEMUSERTYPE_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(20)
)
CREATE TABLE SYSTEMUSER
(
	MANAGER_ID VARCHAR(20) PRIMARY KEY ,
	PASSWORDS VARCHAR(5),
	ID INT,
	PERSON_ID  VARCHAR(20),
	SYSTEMUSERTYPE_ID INT,
	TITLE_ID INT
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID),
	FOREIGN KEY (ID) REFERENCES BRANCH(ID),
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID),
	FOREIGN KEY (SYSTEMUSERTYPE_ID) REFERENCES SYSTEMUSERTYPE(SYSTEMUSERTYPE_ID)
)
CREATE TABLE VOLUNTEER
(
	VOLUNTEER_ID VARCHAR(20) PRIMARY KEY,
	START DATETIME,
	ENDS DATETIME,
	PERSON_ID  VARCHAR(20),
	TITLE_ID INT,
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID),
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID)
)
CREATE TABLE DONOR
(
	DONOR_ID VARCHAR(20)  PRIMARY KEY,
	COMPANY VARCHAR (20),
	COUNTRY VARCHAR(20),
	PERSON_ID  VARCHAR(20),
	TITLE_ID INT,
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID),
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID)
)

CREATE TABLE TCLOTHES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR (20)
)

CREATE TABLE CLOTHES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	SIZE VARCHAR(20),
	TCLOTHES INT,
	QUANTITY INT,
	FOREIGN KEY(TCLOTHES) REFERENCES TCLOTHES(ID)
)

CREATE TABLE TFOOD
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR (20),
)

CREATE TABLE FOOD
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TFOOD INT,
	QUANTITY INT,
	FOREIGN KEY (TFOOD) REFERENCES TFOOD(ID)
)

CREATE TABLE TMONEYS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR (20),
)

CREATE TABLE MONEYS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	AMOUNT INT,
	TMONEYS INT,
	FOREIGN KEY (TMONEYS) REFERENCES TMONEYS(ID)	
)

CREATE TABLE TEVENS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR (20),
)

CREATE TABLE EVEN
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DATES DATETIME,
	AMOUNTRAISED INT,
	TEVENS INT,
	VIDEO VARCHAR(100),
	FOREIGN KEY (TEVENS) REFERENCES TEVENS(ID)
)

CREATE TABLE DONATION
(
	ID VARCHAR (20) PRIMARY KEY,
	DATES DATETIME,
	DESCRIPTIONS VARCHAR (100),
	DONOR_ID VARCHAR(20),
	AMOUNT INT,
	EVEN INT,
	NAME VARCHAR(20)
	FOREIGN KEY(DONOR_ID) REFERENCES DONOR(DONOR_ID),
	FOREIGN KEY (EVEN) REFERENCES EVEN(ID)
)

CREATE TABLE EVENT_IMAGED
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR(20),
	EID INT,
	FOREIGN KEY(EID) REFERENCES EVEN(ID)
)

CREATE TABLE CANDIDATE
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR(20),
	COUNRTY VARCHAR(20),
	REGISTARTIONNUMBER VARCHAR(20),
	CONTACTPERSON VARCHAR(20),
	CONTACTNUM VARCHAR(10)
)

CREATE TABLE SPONSORSHIP
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	AMOUNT INT,
	EVEN INT,
	NAME VARCHAR(20),
	CANDIDDATE VARCHAR(20)
	FOREIGN KEY (EVEN) REFERENCES EVEN(ID)
)