USE MASTER
GO

ALTER DATABASE FEEDAFRICA SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE FEEDAFRICA

CREATE DATABASE FEEDAFRICA
GO
USE FEEDAFRICA
GO

CREATE TABLE TITLE
(
	TITLE_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(20)
)

INSERT INTO TITLE VALUES('Mr')
INSERT INTO TITLE VALUES('Miss')
INSERT INTO TITLE VALUES('Mrs')
INSERT INTO TITLE VALUES('Dr')

CREATE TABLE BRANCH 
(
	ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(20)
)

INSERT INTO BRANCH VALUES('USA')
INSERT INTO BRANCH VALUES('South Africa')
INSERT INTO BRANCH VALUES('Angola')
INSERT INTO BRANCH VALUES('Kenya')

CREATE TABLE EMPLOYEE_TYPE
(
	EMPLOYEE_TYPE_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(20)
)
INSERT INTO EMPLOYEE_TYPE VALUES('Manager')
INSERT INTO EMPLOYEE_TYPE VALUES('CEO')
INSERT INTO EMPLOYEE_TYPE VALUES('Accountant')

CREATE TABLE EMPLOYEE
(
	EMPLOYEE INT PRIMARY KEY IDENTITY(1,1),
	PASSWORDS VARCHAR(5),	
	EMPLOYEE_TYPE_ID INT,
	TITLE_ID INT,
	ID INT,
	NAMED VARCHAR(20),
	SURNAME VARCHAR (20),
	IDENTITY_NUMBER VARCHAR(13),
	EMAIL VARCHAR (50),	
	PHONE VARCHAR (10),
	FOREIGN KEY (ID) REFERENCES BRANCH(ID) ON DELETE SET NULL,
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID)ON DELETE SET NULL,
	FOREIGN KEY (EMPLOYEE_TYPE_ID) REFERENCES EMPLOYEE_TYPE(EMPLOYEE_TYPE_ID)ON DELETE SET NULL
)
CREATE TABLE VOLUNTEER
(
	EMPLOYEE INT PRIMARY KEY IDENTITY(1,1),
	EMPLOYEE_TYPE_ID INT,
	TITLE_ID INT,
	NAMED VARCHAR(20),
	SURNAME VARCHAR (20),
	IDENTITY_NUMBER VARCHAR(13),
	EMAIL VARCHAR (50),	
	PHONE VARCHAR (10),
	STARTING DATETIME,
	ENDING DATETIME
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID)ON DELETE SET NULL
)
CREATE TABLE DONOR
(
	DONOR_ID INT PRIMARY KEY IDENTITY(1,1),
	COMPANY VARCHAR (20),
	COUNTRY VARCHAR(20),
	EMPLOYEE_TYPE_ID INT,
	TITLE_ID INT,
	NAMED VARCHAR(20),
	SURNAME VARCHAR (20),
	IDENTITY_NUMBER VARCHAR(13),
	EMAIL VARCHAR (50),	
	PHONE VARCHAR (10),
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID) ON DELETE SET NULL,
)

CREATE TABLE TEVENS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR (20),
)

INSERT INTO TEVENS VALUES('Donations')
INSERT INTO TEVENS VALUES('Sponsor')

CREATE TABLE EVEN
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DATES DATETIME,
	AMOUNTRAISED INT,
	TEVENS INT,
	VIDEO VARCHAR(100),
	FOREIGN KEY (TEVENS) REFERENCES TEVENS(ID)ON DELETE SET NULL
)

CREATE TABLE CANDIDATE
(
	CANDIDATE_ID INT PRIMARY KEY IDENTITY(1,1),
	cANDIDATE_NAME VARCHAR(20),
	COUNRTY VARCHAR(20),
	REGISTARTIONNUMBER VARCHAR(20),
	CONTACTPERSON VARCHAR(20),
	CONTACTNUM VARCHAR(10)
)

CREATE TABLE DONATION_TYPE
(
	DONATION_TYPE_ID INT PRIMARY KEY IDENTITY(1,1),
	ITEM VARCHAR(20)
)

INSERT INTO DONATION_TYPE VALUES('Clothes')
INSERT INTO DONATION_TYPE VALUES('Food')
INSERT INTO DONATION_TYPE VALUES('Cash')

CREATE TABLE DONATION
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	DATES DATETIME,
	DONOR_ID INT,	
	EVEN INT,
	DONATION_TYPE_ID INT,
	AMOUNT INT,
	FOREIGN KEY (DONATION_TYPE_ID) REFERENCES DONATION_TYPE(DONATION_TYPE_ID)ON DELETE SET NULL,	
	FOREIGN KEY(DONOR_ID) REFERENCES DONOR(DONOR_ID)ON DELETE SET NULL,
	FOREIGN KEY (EVEN) REFERENCES EVEN(ID)ON DELETE SET NULL
)

CREATE TABLE SPONSORSHIP
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	AMOUNT INT,
	EVEN INT,
	NAME VARCHAR(20),
	SPONSORSHIP_DATE VARCHAR(20),
	CANDIDATE_ID INT,
	DONATION_TYPE_ID INT,
	FOREIGN KEY (EVEN) REFERENCES EVEN(ID)ON DELETE SET NULL,
	FOREIGN KEY (CANDIDATE_ID) REFERENCES CANDIDATE(CANDIDATE_ID)ON DELETE SET NULL,
	FOREIGN KEY (DONATION_TYPE_ID) REFERENCES DONATION_TYPE(DONATION_TYPE_ID)ON DELETE SET NULL
)