//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANDIDATE()
        {
            this.SPONSORSHIPs = new HashSet<SPONSORSHIP>();
        }
    
        public int CANDIDATE_ID { get; set; }
        public string cANDIDATE_NAME { get; set; }
        public string COUNRTY { get; set; }
        public string REGISTARTIONNUMBER { get; set; }
        public string CONTACTPERSON { get; set; }
        public string CONTACTNUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPONSORSHIP> SPONSORSHIPs { get; set; }
    }
}
