//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FEEDAFRICAEntities : DbContext
    {
        public FEEDAFRICAEntities()
            : base("name=FEEDAFRICAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANCH> BRANCHes { get; set; }
        public virtual DbSet<CANDIDATE> CANDIDATEs { get; set; }
        public virtual DbSet<DONATION> DONATIONs { get; set; }
        public virtual DbSet<DONATION_TYPE> DONATION_TYPE { get; set; }
        public virtual DbSet<DONOR> DONORs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<EMPLOYEE_TYPE> EMPLOYEE_TYPE { get; set; }
        public virtual DbSet<EVEN> EVENs { get; set; }
        public virtual DbSet<SPONSORSHIP> SPONSORSHIPs { get; set; }
        public virtual DbSet<TEVEN> TEVENS { get; set; }
        public virtual DbSet<TITLE> TITLEs { get; set; }
        public virtual DbSet<VOLUNTEER> VOLUNTEERs { get; set; }
    }
}
